### ISSUE TITLE
Cannot install...

### ISSUE THREAD

**Issue by kibeomkim-0728** [TfT-02/DynamicTextures#15]
This is 1.8.7 server, and

```
[00:07:09] [Server thread/INFO]: [DynamicTextures] Enabling DynamicTextures v1.3.4
[00:07:09] [Server thread/INFO]: [DynamicTextures] WorldGuard found!
[00:07:10] [Server thread/ERROR]: Error occurred while enabling DynamicTextures v1.3.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/mcstats/Metrics
        at com.me.tft_02.dynamictextures.DynamicTextures.setupMetrics(DynamicTextures.java:139) ~[?:?]
        at com.me.tft_02.dynamictextures.DynamicTextures.onEnable(DynamicTextures.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: org.mcstats.Metrics
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server-apocalypse.jar:git-Spigot-44c59bf-8f0f4ed]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
        ... 13 more
```

**Comment by sheerlox** [comment]
Have the same ...
